### ISSUE TITLE
css not linked properly

### ISSUE THREAD

**Issue by blackgwe** [ChrisBauer/aurelia-grid#2]
Hi Chris! 

Thanks for your aurelia-grid implementation. Do you want to keep it up to date? Currently it's broken:

http://localhost:9000/dist/css/grid/aurelia-grid.css
==> Cannot GET /dist/css/grid/aurelia-grid.css

use <link rel="stylesheet" href="grid.css">  (see http://aurelia.io/docs.html#templating )

Thank you very much!

**Comment by ChrisBauer** [comment]
Thanks for catching this! I'm going to have another commit in the next day or two to get up to speed with the latest Aurelia release
